### PR TITLE
A couple of fixes for version 3 of the APK

### PR DESCRIPTION
**Pull request by annoyingmouse**
Downloading it caused some issues so I guess the new SDK isn't backwards compatible. :-(

I'll work on the waiter when I'm free tomorrow.

### CODE REVIEW

**Comment by annoyingmouse** [comment]
Script now working and generating tables with no errors using the latest AWS SDK for PHP

**Comment by annoyingmouse** [comment]
uploaddata.php also fixed now

**Comment by holdorph** [comment]
I don't know php.  When I was looking at the differences in these files, I noticed the closing question mark  bracket ?>  is missing from both files.  Is that needed?  Is there any harm in it being there?

**Comment by annoyingmouse** [comment]
Hi @holdorph, the closing "?>" is not required. Please see: http://stackoverflow.com/questions/4410704/why-would-one-omit-the-close-tag

**Comment by holdorph** [comment]
I'm not a PHP developer, so my apologies.  I was basing my comment solely off of the fact that the code this PR was created from was closing the tag.

**Comment by annoyingmouse** [comment]
Hey @holdorph, don't worry about it! It's always good to ask questions! Take it easy :-)

**Comment by ghost** [comment]
I fully tested the scripts and they work fine as per the Lab now.
Rusty

**Pull request closed without merging**
